[tool.pygbag]
entrypoint = "main.py"

# Keep assets exactly where they are
assets = [
    "assets/**"
]

title = "Gyroad"

# 0 = let your Python code decide canvas size
canvas_width = 0
canvas_height = 0